### ISSUE TITLE
No module named 'utils.test.nms.gpu_nms'

### ISSUE THREAD

**Issue by pprp** [TencentYoutuResearch/ObjectDetection-OneStageDet#44]
你好，我按照你的说明配置了VOC2007但是遇到以下问题。
```
ObjectDetection-OneStageDet-master/yolo$ python examples/train.py Yolov3
Traceback (most recent call last):
  File "examples/train.py", line 15, in <module>
    import vedanet as vn
  File "./vedanet/__init__.py", line 13, in <module>
    from . import engine
  File "./vedanet/engine/__init__.py", line 10, in <module>
    from ._voc_test import *
  File "./vedanet/engine/_voc_test.py", line 10, in <module>
    from utils.test import voc_wrapper
  File "./utils/test/voc_wrapper.py", line 4, in <module>
    from .fast_rcnn.nms_wrapper import nms, soft_nms
  File "./utils/test/fast_rcnn/nms_wrapper.py", line 8, in <module>
    from ..nms.gpu_nms import gpu_nms
ModuleNotFoundError: No module named 'utils.test.nms.gpu_nms'
```
我查看了这个文件，发现这个gpu_nms文件是一个pyx类型的文件，能否提供原本的py文件啊，或者如何解决这个问题，感激不尽

**Comment by mileistone** [comment]
did you run `make` command?

**Comment by pprp** [comment]
Yes, I run this command and there is no error

**Comment by mileistone** [comment]
You can comment this line, just use cpu nms.
