### ISSUE TITLE
ImportError: ./utils/test/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by lunasdejavu** [TencentYoutuResearch/ObjectDetection-OneStageDet#87]
environment: 
python: 3.6.8
pytorch: 0.4.1
ubuntu:Ubuntu 16.04.6 LTS
GPU:
I tried `python3 examples/train.py Yolo2`
```
Traceback (most recent call last):
  File "examples/train.py", line 15, in <module>
    import vedanet as vn
  File "./vedanet/__init__.py", line 13, in <module>
    from . import engine
  File "./vedanet/engine/__init__.py", line 10, in <module>
    from ._voc_test import *
  File "./vedanet/engine/_voc_test.py", line 10, in <module>
    from utils.test import voc_wrapper
  File "./utils/test/voc_wrapper.py", line 4, in <module>
    from .fast_rcnn.nms_wrapper import nms, soft_nms
  File "./utils/test/fast_rcnn/nms_wrapper.py", line 8, in <module>
    from ..nms.gpu_nms import gpu_nms
ImportError: ./utils/test/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

```

**Comment by lunasdejavu** [comment]
solve the issue by #15 just changed `python `to` python3 `in Makefile
