### ISSUE TITLE
something worng about Train own dataset

### ISSUE THREAD

**Issue by ClayZhang0403** [TencentYoutuResearch/ObjectDetection-OneStageDet#91]
when i use label.py to make up train.pkl and test.pkl , and then to modify yolov3.yml and use python examples/train.py Yolov3 ,but this wrong 
2019-08-16 13:27:43,374:INFO:No 'keep_ignore' kwarg found, defaulting to False.
Traceback (most recent call last):
  File "./vedanet/data/_dataset_brambox.py", line 51, in __init__
    a.class_id = class_label_map.index(a.class_label)
ValueError: 'y' is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/train.py", line 35, in <module>
    eng = vn.engine.VOCTrainingEngine(hyper_params)
  File "./vedanet/engine/_voc_train.py", line 69, in __init__
    dataset = VOCDataset(hyper_params)
  File "./vedanet/engine/_voc_train.py", line 35, in __init__
    super(VOCDataset, self).__init__('anno_pickle', anno, network_size, labels, identify, img_tf, anno_tf)
  File "./vedanet/data/_dataset_brambox.py", line 53, in __init__
    raise ValueError(f'{a.class_label} is not found in the class_label_map') from err
ValueError: y is not found in the class_label_map

_________
当我按照教程用label.py去把自己的数据生成pkl后，然后按照流程去修改yml然后运行 就会报如上述的错误，请问我是有什么地方遗漏吗

**Comment by ClayZhang0403** [comment]
刚刚那个已经解决 ， 现在遇到这样的问题在执行python examples/train.py Yolov3时出现了FileNotFoundError: [Errno 2] No such file or directory: '/VOCdevkit/text/JPEGImages/sesa.jpg'的问题，text文件目录是怎么来的？我并没有在VOCdevkit中创建过text文件夹???

**Comment by ClayZhang0403** [comment]
那个也解决了  但是在训练的时候一直出现这个 是什么原因
2019-08-16 15:51:11,894:DEBUG:STREAM b'pHYs' 41 9
2019-08-16 15:51:11,894:DEBUG:STREAM b'IDAT' 62 8192
2019-08-16 15:51:11,903:DEBUG:STREAM b'IHDR' 16 13
2019-08-16 15:51:11,903:DEBUG:STREAM b'pHYs' 41 9
2019-08-16 15:51:11,903:DEBUG:STREAM b'IDAT' 62 8192
2019-08-16 15:51:11,943:DEBUG:STREAM b'IHDR' 16 13
2019-08-16 15:51:11,943:DEBUG:STREAM b'pHYs' 41 9
2019-08-16 15:51:11,943:DEBUG:STREAM b'IDAT' 62 8192
2019-08-16 15:51:11,996:DEBUG:STREAM b'IHDR' 16 13

**Comment by IrisDinge** [comment]
> 那个也解决了 但是在训练的时候一直出现这个 是什么原因
> 2019-08-16 15:51:11,894:DEBUG:STREAM b'pHYs' 41 9
> 2019-08-16 15:51:11,894:DEBUG:STREAM b'IDAT' 62 8192
> 2019-08-16 15:51:11,903:DEBUG:STREAM b'IHDR' 16 13
> 2019-08-16 15:51:11,903:DEBUG:STREAM b'pHYs' 41 9
> 2019-08-16 15:51:11,903:DEBUG:STREAM b'IDAT' 62 8192
> 2019-08-16 15:51:11,943:DEBUG:STREAM b'IHDR' 16 13
> 2019-08-16 15:51:11,943:DEBUG:STREAM b'pHYs' 41 9
> 2019-08-16 15:51:11,943:DEBUG:STREAM b'IDAT' 62 8192
> 2019-08-16 15:51:11,996:DEBUG:STREAM b'IHDR' 16 13

请问，是什么原因，我在按照格式训练自己的数据集时也出现了这样的提示？Thks

**Comment by Noah-CV** [comment]
> 刚刚那个已经解决 ， 现在遇到这样的问题在执行python examples/train.py Yolov3时出现了FileNotFoundError: [Errno 2] No such file or directory: '/VOCdevkit/text/JPEGImages/sesa.jpg'的问题，text文件目录是怎么来的？我并没有在VOCdevkit中创建过text文件夹???

请问您这个读取问题是怎么解决的，我的VOC2007读取出来每次都不一样 pa nr什么的

**Comment by Aurorayy** [comment]
> 刚刚那个已经解决 ， 现在遇到这样的问题在执行python examples/train.py Yolov3时出现了FileNotFoundError: [Errno 2] No such file or directory: '/VOCdevkit/text/JPEGImages/sesa.jpg'的问题，text文件目录是怎么来的？我并没有在VOCdevkit中创建过text文件夹???

请问这个是怎么解决的？

**Comment by ZzWhiteMoon** [comment]
> when i use label.py to make up train.pkl and test.pkl , and then to modify yolov3.yml and use python examples/train.py Yolov3 ,but this wrong 2019-08-16 13:27:43,374:INFO:No 'keep_ignore' kwarg found, defaulting to False. Traceback (most recent call last): File "./vedanet/data/_dataset_brambox.py", line 51, in **init** a.class_id = class_label_map.index(a.class_label) ValueError: 'y' is not in list
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "examples/train.py", line 35, in eng = vn.engine.VOCTrainingEngine(hyper_params) File "./vedanet/engine/_voc_train.py", line 69, in **init** dataset = VOCDataset(hyper_params) File "./vedanet/engine/_voc_train.py", line 35, in **init** super(VOCDataset, self).**init**('anno_pickle', anno, network_size, labels, identify, img_tf, anno_tf) File "./vedanet/data/_dataset_brambox.py", line 53, in **init** raise ValueError(f'{a.class_label} is not found in the class_label_map') from err ValueError: y is not found in the class_label_map
> 
> 当我按照教程用label.py去把自己的数据生成pkl后，然后按照流程去修改yml然后运行 就会报如上述的错误，请问我是有什么地方遗漏吗

哥这个问题是怎么解决的？
Bro, could you tell me how to fix this fxxking error :)
